// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmbyjqlowntmxpbmaldx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtYnlqcWxvd250bXhwYm1hbGR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDcyMjMsImV4cCI6MjA2NTY4MzIyM30.cPjubr873WcugNDSONN_b-Y94IEsbuB5021TKh6bLjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);